apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ printf "%s-jwt" (include "common.names.fullname" .) | trunc 63 | trimSuffix "-" }}
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
  {{- if .Values.commonLabels }}
  {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
  {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  accessModes:
  {{- range .Values.persistence_jwt.accessModes }}
    - {{ . | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence_jwt.size | quote }}
  {{- include "common.storage.class" (dict "persistence_jwt" .Values.persistence_jwt "global" .Values.global) | nindent 2 }}
  {{- if .Values.persistence_jwt.dataSource }}
  dataSource: {{- include "common.tplvalues.render" (dict "value" .Values.persistence_jwt.dataSource "context" $) | nindent 4 }}
  {{- end }}
